config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  
  resources :users, only: [:new, :create, :update, :edit, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :email, presence: false
  validates :password, presence: false, length: { in: 6..16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path(@user)
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
  <%= form_with model: @user do |form| %>
  <p>
      <%= form.label :username, "Username:" %>
      <%= form.text_field :username, :value => @user.username %><br><br>
  </p>
  <p>
      <%= form.label :password, "Password:" %>
      <%= form.password_field :password, :value => @user.password %><br><br>
  </p>
  <p>
      <%= form.label :email, "Email:" %>
      <%= form.text_field :email, :value => @user.email %><br><br>
  </p>
  <p>
      <%= form.submit "Submit" %>
  </p>
  <p>
      <%= link_to "All Users", root_path %><br />
  </p>
  <% end %>

app/views/users/edit.html.erb
<!-- <form action="/users" method="post" accept-charset="UTF-8">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br><br>
  <label for="username" >Username:</label>
  <input type="text" id="username" name="user[username]" ><br><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"><br><br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]"><br><br>
  <input type="submit" value="Submit">
</form> -->
<!-- <%= form_tag("/users", method: "post") do %>
  <br><br>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %><br><br>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %><br><br>
  <%= label_tag(:email, "Email:") %>
  <%= text_field_tag(:email) %><br><br>

  <%= submit_tag "Submit" %>
<% end %><%= form_with model: @user, url: edit_user_path(@user), method: :patch do |form| %>
  <br><br>
  <%= form.label :username, "Edit Username:" %>
  <%= form.text_field :username, :value => @user.username %><br><br>
  <%= form.label :email, "Edit Email:" %>
  <%= form.text_field :email, :value => @user.email %><br><br>
  <%= form.label :password, "Edit Password:" %>
  <%= form.password_field :password %><br><br>
  <%= form.submit "Submit" %>
<% end %>
<br><br>
<%= link_to "All Users", root_path %><br/> -->
<h1>Edit User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
    <% @users.each do |user| %>
    <li>
        <%= link_to user.username, user_path(user) %>
    </li>
    <% end %>
</ul>
<%= link_to "New User", new_user_path %><br />

app/views/users/new.html.erb
<!-- <form action="/users" method="post" accept-charset="UTF-8">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br><br>
  <label for="username" >Username:</label>
  <input type="text" id="username" name="user[username]" ><br><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"><br><br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]"><br><br>
  <input type="submit" value="Submit">
</form> -->
<!-- <%= form_tag("/users", method: "post") do %>
  <br><br>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %><br><br>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %><br><br>
  <%= label_tag(:email, "Email:") %>
  <%= text_field_tag(:email) %><br><br>

  <%= submit_tag "Submit" %>
<% end %> -->
<!-- <%= form_with model: @user, method: :post do |form| %>
  <br><br>
  <%= form.label :username, "Username:" %>
  <%= form.text_field :username %><br><br>
  <%= form.label :password, "Password:" %>
  <%= form.label :email, "Email:" %>
  <%= form.text_field :email %><br><br>
  <%= form.password_field :password %><br><br>
  <%= form.submit "Submit" %>
<% end %>
<br><br>
<%= link_to "Home", root_path %><br/> -->
<h1>Create User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p><%= @user.email %></p>
<%= link_to "Edit", edit_user_path(@user) %>
<br><br>
<%= link_to "Home", root_path %><br />